apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas : 2
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: veerasolaiyappan/my-node-app:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000